//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontur.GameStats.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Match()
        {
            this.ScoreBoard = new HashSet<ScoreBoard>();
        }
    
        public int MatchID { get; set; }
        public int ServerID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int GameModeID { get; set; }
        public int Population { get; set; }
        public Nullable<int> FragLimit { get; set; }
        public Nullable<int> TimeLimit { get; set; }
        public float TimeElapsed { get; set; }
        public int MapID { get; set; }
    
        public virtual GameMode GameMode { get; set; }
        public virtual Map Map { get; set; }
        public virtual Server Server { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoreBoard> ScoreBoard { get; set; }
    }
}
