//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontur.GameStats.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerStatsOnServer
    {
        public int PlayerID { get; set; }
        public int ServerID { get; set; }
        public Nullable<int> PlayCount { get; set; }
        public Nullable<int> WinsCount { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Server Server { get; set; }
    }
}
