//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontur.GameStats.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.PlayerMatchesPerDay = new HashSet<PlayerMatchesPerDay>();
            this.PlayerStatsOnGameMode = new HashSet<PlayerStatsOnGameMode>();
            this.PlayerStatsOnServer = new HashSet<PlayerStatsOnServer>();
            this.ScoreBoards = new HashSet<ScoreBoard>();
        }
    
        public int PlayerId { get; set; }
        public string NickName { get; set; }
        public string DisplayNickName { get; set; }
        public byte[] LastMatchPlayed { get; set; }
        public Nullable<int> TotalMatchesPlayed { get; set; }
        public Nullable<int> TotalMatchesWon { get; set; }
        public Nullable<float> AvScoreBoardPercent { get; set; }
        public Nullable<int> TotalKills { get; set; }
        public Nullable<int> TotalDeaths { get; set; }
        public Nullable<int> MaxMatchesPerDay { get; set; }
        public Nullable<int> KD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerMatchesPerDay> PlayerMatchesPerDay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerStatsOnGameMode> PlayerStatsOnGameMode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerStatsOnServer> PlayerStatsOnServer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoreBoard> ScoreBoards { get; set; }
    }
}
