//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontur.GameStats.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreBoard
    {
        public int MatchID { get; set; }
        public int PlayerID { get; set; }
        public Nullable<int> Frags { get; set; }
        public Nullable<int> Kills { get; set; }
        public Nullable<int> Deaths { get; set; }
        public Nullable<int> Place { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Player Player { get; set; }
    }
}
