//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontur.GameStats.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerMatchesPerDay
    {
        public int ServerID { get; set; }
        public System.DateTime DayID { get; set; }
        public Nullable<int> MatchesCount { get; set; }
        public Nullable<int> TotalPopulation { get; set; }
    
        public virtual Server Server { get; set; }
    }
}
