//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontur.GameStats.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Server
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Server()
        {
            this.Matches = new HashSet<Match>();
            this.PlayerStatsOnServer = new HashSet<PlayerStatsOnServer>();
            this.ServerGameModes = new HashSet<ServerGameModes>();
            this.ServerMatchesPerDay = new HashSet<ServerMatchesPerDay>();
            this.ServerTopMaps = new HashSet<ServerTopMaps>();
        }
    
        public int ServerId { get; set; }
        public string EndPoint { get; set; }
        public string ServerName { get; set; }
        public Nullable<int> MatchesCount { get; set; }
        public Nullable<int> MaxPopulation { get; set; }
        public Nullable<int> TotalPopulation { get; set; }
        public Nullable<int> MaxMatchesPerDay { get; set; }
        public Nullable<int> DaysCount { get; set; }
        public string GameModes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match> Matches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerStatsOnServer> PlayerStatsOnServer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServerGameModes> ServerGameModes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServerMatchesPerDay> ServerMatchesPerDay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServerTopMaps> ServerTopMaps { get; set; }
    }
}
