//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontur.GameStats.Server
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StatisticbaseContext : DbContext
    {
        public StatisticbaseContext()
            : base("name=StatisticbaseContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GameMode> GameMode { get; set; }
        public virtual DbSet<Map> Map { get; set; }
        public virtual DbSet<Match> Match { get; set; }
        public virtual DbSet<PlayerMatchesPerDay> PlayerMatchesPerDay { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<PlayerStatsOnGameMode> PlayerStatsOnGameMode { get; set; }
        public virtual DbSet<PlayerStatsOnServer> PlayerStatsOnServer { get; set; }
        public virtual DbSet<ScoreBoard> ScoreBoard { get; set; }
        public virtual DbSet<ServerGameModes> ServerGameModes { get; set; }
        public virtual DbSet<ServerMatchesPerDay> ServerMatchesPerDay { get; set; }
        public virtual DbSet<Server> Server { get; set; }
        public virtual DbSet<ServerTopMaps> ServerTopMaps { get; set; }
    }
}
